// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type Colonies struct {
	ID       int64
	PlanetID int64
	Kind     string
	Location string
}

type Deposit struct {
	DepositID int64
	Quantity  int64
	YieldPct  int64
	EffTurn   int64
	EndTurn   int64
	Active    int64
}

type Deposits struct {
	ID           int64
	PlanetID     int64
	DepositNo    int64
	Kind         string
	YieldPct     int64
	InitialQty   int64
	RemainingQty int64
}

type Empires struct {
	ID           int64
	GameID       int64
	EmpireNo     int64
	Name         string
	HomeSystemID int64
	HomeStarID   int64
	HomeOrbitID  int64
	HomePlanetID int64
}

type Games struct {
	ID          int64
	Code        string
	Name        string
	DisplayName string
	CurrentTurn int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Orbits struct {
	ID       int64
	StarID   int64
	OrbitNo  int64
	Kind     string
	Scarcity int64
}

type Planets struct {
	ID           int64
	OrbitID      int64
	Kind         string
	Habitability int64
	Scarcity     int64
}

type Stars struct {
	ID       int64
	SystemID int64
	Sequence string
	Scarcity int64
}

type SystemDistances struct {
	FromSystemID int64
	ToSystemID   int64
	Distance     int64
}

type Systems struct {
	ID       int64
	GameID   int64
	X        int64
	Y        int64
	Z        int64
	Scarcity int64
}
