// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Clusters struct {
	GameID       int64
	ID           int64
	HomeSystemID int64
	HomeStarID   int64
	HomeOrbitID  int64
	HomePlanetID int64
}

type Deposits struct {
	PlanetID     int64
	ID           int64
	DepositNo    int64
	Kind         string
	RemainingQty int64
	YieldPct     int64
}

type Empires struct {
	GameID       int64
	UserID       int64
	ID           int64
	IsActive     int64
	EmpireNo     int64
	Name         string
	HomeSystemID int64
	HomeStarID   int64
	HomeOrbitID  int64
	HomePlanetID int64
}

type FactoryGroup struct {
	FactoryGroupID  int64
	ID              int64
	UnitCd          string
	TechLevel       int64
	NbrOfUnits      int64
	OrdersCd        string
	OrdersTechLevel int64
	Wip25pctQty     int64
	Wip50pctQty     int64
	Wip75pctQty     int64
}

type FactoryGroups struct {
	SorcID          int64
	ID              int64
	GroupNo         int64
	OrdersCd        string
	OrdersTechLevel int64
	RetoolTurnNo    sql.NullInt64
}

type FarmGroup struct {
	FarmGroupID int64
	ID          int64
	UnitCd      string
	TechLevel   int64
	NbrOfUnits  int64
}

type FarmGroups struct {
	SorcID  int64
	ID      int64
	GroupNo int64
}

type Games struct {
	ID           int64
	Code         string
	Name         string
	DisplayName  string
	CurrentTurn  int64
	LastEmpireNo int64
	IsActive     int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Inventory struct {
	SorcID      int64
	UnitCd      string
	TechLevel   int64
	Qty         int64
	Mass        float64
	Volume      float64
	IsAssembled int64
	IsStored    int64
}

type MetaMigrations struct {
	Version   int64
	Comment   string
	Script    string
	CreatedAt time.Time
}

type MiningGroup struct {
	MiningGroupID int64
	ID            int64
	UnitCd        string
	TechLevel     int64
	NbrOfUnits    int64
}

type MiningGroups struct {
	SorcID    int64
	DepositID int64
	ID        int64
	GroupNo   int64
}

type OrbitCodes struct {
	Code string
	Name string
}

type Orbits struct {
	StarID  int64
	ID      int64
	OrbitNo int64
	Kind    string
}

type PlanetCodes struct {
	Code string
	Name string
}

type Planets struct {
	OrbitID      int64
	ID           int64
	Kind         string
	Habitability int64
}

type Population struct {
	SorcID       int64
	PopulationCd string
	Qty          int64
	PayRate      float64
	RebelQty     int64
}

type PopulationCodes struct {
	Code        string
	Name        string
	BasePayRate float64
	SortOrder   int64
}

type ProbeOrders struct {
	SorcID    int64
	TurnNo    int64
	TechLevel int64
	Kind      string
	TargetID  int64
	Status    sql.NullString
}

type ReportProbeSorcs struct {
	ID       int64
	ReportID int64
	EmpireID int64
	SorcID   int64
	SorcCd   string
	SorcMass int64
}

type ReportProbes struct {
	ID           int64
	ReportID     int64
	OrbitID      int64
	Habitability int64
	FuelQty      int64
	GoldQty      int64
	MetalsQty    int64
	NonMetalsQty int64
}

type ReportProductionInputs struct {
	ReportID  int64
	ID        int64
	Category  string
	Fuel      int64
	Gold      int64
	Metals    int64
	NonMetals int64
}

type ReportProductionOutputs struct {
	ReportID     int64
	ID           int64
	Category     string
	UnitCd       string
	TechLevel    int64
	Farmed       int64
	Mined        int64
	Manufactured int64
}

type ReportSpies struct {
	ReportID int64
	ID       int64
}

type ReportSurveyDeposits struct {
	ReportID        int64
	DepositNo       int64
	DepositQty      int64
	DepositKind     string
	DepositYieldPct int64
}

type ReportSurveys struct {
	ID       int64
	ReportID int64
	OrbitID  int64
}

type Reports struct {
	SorcID int64
	ID     int64
	TurnNo int64
}

type SorcCodes struct {
	Code string
	Name string
}

type Sorcs struct {
	EmpireID    int64
	ID          int64
	SorcCd      string
	TechLevel   int64
	Name        string
	OrbitID     int64
	IsOnSurface int64
	Rations     float64
	Sol         float64
	BirthRate   float64
	DeathRate   float64
}

type Stars struct {
	SystemID int64
	ID       int64
	Sequence string
}

type SurveyOrders struct {
	SorcID    int64
	TurnNo    int64
	TechLevel int64
	OrbitID   int64
	Status    sql.NullString
}

type SystemDistances struct {
	FromSystemID int64
	ToSystemID   int64
	Distance     int64
}

type Systems struct {
	ClusterID int64
	ID        int64
	X         int64
	Y         int64
	Z         int64
}

type UnitCodes struct {
	Code          string
	Name          string
	Category      string
	IsOperational int64
	IsConsumable  int64
	IsResource    int64
	Aliases       sql.NullString
}

type Users struct {
	ID             int64
	Username       string
	Email          string
	HashedPassword string
	IsActive       int64
	IsAdmin        int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
