// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type Clusters struct {
	GameID       int64
	ID           int64
	HomeSystemID int64
	HomeStarID   int64
	HomeOrbitID  int64
	HomePlanetID int64
}

type Deposits struct {
	PlanetID     int64
	ID           int64
	DepositNo    int64
	Kind         string
	RemainingQty int64
	YieldPct     int64
}

type Empires struct {
	GameID       int64
	UserID       int64
	ID           int64
	IsActive     int64
	EmpireNo     int64
	Name         string
	HomeSystemID int64
	HomeStarID   int64
	HomeOrbitID  int64
	HomePlanetID int64
}

type FactoryGroup struct {
	FactoryGroupID int64
	ID             int64
	UnitCd         string
	NbrOfUnits     int64
	Wip25pctQty    int64
	Wip50pctQty    int64
	Wip75pctQty    int64
}

type FactoryGroups struct {
	SorcID       int64
	ID           int64
	GroupNo      int64
	RetoolTurnNo sql.NullInt64
	OrdersCd     string
}

type FarmGroup struct {
	FarmGroupID int64
	ID          int64
	UnitCd      string
	NbrOfUnits  int64
}

type FarmGroups struct {
	SorcID  int64
	ID      int64
	GroupNo int64
}

type Games struct {
	ID           int64
	Code         string
	Name         string
	DisplayName  string
	CurrentTurn  int64
	LastEmpireNo int64
	IsActive     int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Inventory struct {
	SorcID int64
	UnitCd string
	Qty    int64
}

type MetaMigrations struct {
	Version   int64
	Comment   string
	Script    string
	CreatedAt time.Time
}

type MiningGroup struct {
	MiningGroupID int64
	ID            int64
	UnitCd        string
	NbrOfUnits    int64
}

type MiningGroups struct {
	SorcID    int64
	DepositID int64
	ID        int64
	GroupNo   int64
}

type OrbitCodes struct {
	Code string
	Name string
}

type Orbits struct {
	StarID  int64
	ID      int64
	OrbitNo int64
	Kind    string
}

type PlanetCodes struct {
	Code string
	Name string
}

type Planets struct {
	OrbitID      int64
	ID           int64
	Kind         string
	Habitability int64
}

type Population struct {
	SorcID       int64
	PopulationCd string
	Qty          int64
	PayRate      float64
	RebelQty     int64
}

type PopulationCodes struct {
	Code        string
	Name        string
	BasePayRate float64
}

type ReportProbes struct {
	ReportID int64
	ID       int64
}

type ReportSpies struct {
	ReportID int64
	ID       int64
}

type ReportSurveys struct {
	ReportID int64
	ID       int64
}

type Reports struct {
	SorcID int64
	ID     int64
	TurnNo int64
}

type SorcCodes struct {
	Code string
	Name string
}

type Sorcs struct {
	EmpireID    int64
	ID          int64
	SorcCd      string
	TechLevel   int64
	Name        string
	OrbitID     int64
	IsOnSurface int64
	Rations     float64
	Sol         float64
	BirthRate   float64
	DeathRate   float64
}

type Stars struct {
	SystemID int64
	ID       int64
	Sequence string
}

type SystemDistances struct {
	FromSystemID int64
	ToSystemID   int64
	Distance     int64
}

type Systems struct {
	ClusterID int64
	ID        int64
	X         int64
	Y         int64
	Z         int64
}

type UnitCodes struct {
	Code      string
	TechLevel int64
	Name      string
	Category  string
}

type Users struct {
	ID        int64
	Handle    string
	MagicLink string
	IsActive  int64
	IsAdmin   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}
