// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: orbits.sql

package sqlc

import (
	"context"
)

const createOrbit = `-- name: CreateOrbit :one
INSERT INTO orbits (star_id, orbit_no, kind)
VALUES (?1, ?2, ?3)
RETURNING id
`

type CreateOrbitParams struct {
	StarID  int64
	OrbitNo int64
	Kind    string
}

// CreateOrbit creates a new orbit.
func (q *Queries) CreateOrbit(ctx context.Context, arg CreateOrbitParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createOrbit, arg.StarID, arg.OrbitNo, arg.Kind)
	var id int64
	err := row.Scan(&id)
	return id, err
}
