// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: planets.sql

package sqlc

import (
	"context"
)

const createPlanet = `-- name: CreatePlanet :one

INSERT INTO planets (orbit_id, kind, habitability)
VALUES (?1, ?2, ?3)
RETURNING id
`

type CreatePlanetParams struct {
	OrbitID      int64
	Kind         string
	Habitability int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// CreatePlanet creates a new planet.
func (q *Queries) CreatePlanet(ctx context.Context, arg CreatePlanetParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createPlanet, arg.OrbitID, arg.Kind, arg.Habitability)
	var id int64
	err := row.Scan(&id)
	return id, err
}
