// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: players.sql

package sqlc

import (
	"context"
)

const readPlayerByHandle = `-- name: ReadPlayerByHandle :one

SELECT id, magic_link, is_active
FROM players
WHERE handle = ?1
`

type ReadPlayerByHandleRow struct {
	ID        int64
	MagicLink string
	IsActive  int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// ReadPlayerByHandle gets a player by its handle.
func (q *Queries) ReadPlayerByHandle(ctx context.Context, handle string) (ReadPlayerByHandleRow, error) {
	row := q.db.QueryRowContext(ctx, readPlayerByHandle, handle)
	var i ReadPlayerByHandleRow
	err := row.Scan(&i.ID, &i.MagicLink, &i.IsActive)
	return i, err
}
