// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: users.sql

package sqlc

import (
	"context"
)

const readUserByHandle = `-- name: ReadUserByHandle :one

SELECT id, magic_link, is_active
FROM users
WHERE handle = ?1
`

type ReadUserByHandleRow struct {
	ID        int64
	MagicLink string
	IsActive  int64
}

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// ReadUserByHandle gets a player by its handle.
func (q *Queries) ReadUserByHandle(ctx context.Context, handle string) (ReadUserByHandleRow, error) {
	row := q.db.QueryRowContext(ctx, readUserByHandle, handle)
	var i ReadUserByHandleRow
	err := row.Scan(&i.ID, &i.MagicLink, &i.IsActive)
	return i, err
}
