// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
	"time"
)

type DepositHistory struct {
	DepositID int64
	Effdt     int64
	Enddt     int64
	Qty       int64
}

type Deposits struct {
	ID        int64
	OrbitID   int64
	DepositNo int64
	Kind      string
	YieldPct  int64
}

type DepositsSummary struct {
	OrbitID    int64
	Effdt      int64
	Enddt      int64
	FuelQty    int64
	FuelEstQty int64
	GoldQty    int64
	GoldEstQty int64
	MetsQty    int64
	MetsEstQty int64
	NmtsQty    int64
	NmtsEstQty int64
}

type DepositsSummaryPivot struct {
	DepositID  int64
	Effdt      int64
	Enddt      int64
	FuelQty    int64
	FuelEstQty int64
	GoldQty    int64
	GoldEstQty int64
	MetsQty    int64
	MetsEstQty int64
	NmtsQty    int64
	NmtsEstQty int64
}

type Empire struct {
	ID           int64
	HomeSystemID int64
	HomeStarID   int64
	HomeOrbitID  int64
	IsActive     int64
}

type EmpireName struct {
	EmpireID int64
	Effdt    int64
	Enddt    int64
	Name     string
}

type EmpirePlayer struct {
	EmpireID int64
	Effdt    int64
	Enddt    int64
	Username string
	Email    string
}

type EmpireStarName struct {
	EmpireID int64
	StarID   int64
	Effdt    int64
	Enddt    int64
	Name     string
}

type EmpireSystemName struct {
	EmpireID int64
	SystemID int64
	Effdt    int64
	Enddt    int64
	Name     string
}

type Games struct {
	Code         string
	Name         string
	DisplayName  string
	CurrentTurn  int64
	HomeSystemID int64
	HomeStarID   int64
	HomeOrbitID  int64
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MetaMigrations struct {
	Version   int64
	Comment   string
	Script    string
	CreatedAt time.Time
}

type OrbitCodes struct {
	Code string
	Name string
}

type Orbits struct {
	ID            int64
	SystemID      int64
	StarID        int64
	OrbitNo       int64
	Kind          string
	Habitability  int64
	NbrOfDeposits int64
}

type PopulationCodes struct {
	Code        string
	Name        string
	BasePayRate float64
	SortOrder   int64
}

type ScCodes struct {
	Code      string
	Name      string
	IsShip    int64
	IsSurface int64
}

type ScGroup struct {
	ID    int64
	ScID  int64
	Kind  string
	Effdt int64
	Enddt int64
}

type ScGroupDeposit struct {
	GroupID   int64
	Effdt     int64
	Enddt     int64
	DepositID int64
}

type ScGroupNo struct {
	GroupID int64
	Effdt   int64
	Enddt   int64
	GroupNo int64
}

type ScGroupProductionSummary struct {
	GroupID      int64
	ProductionDt int64
	FuelConsumed int64
	GoldConsumed int64
	MetsConsumed int64
	NmtsConsumed int64
	ProConsumed  int64
	UskConsumed  int64
	AutConsumed  int64
	QtyProduced  int64
}

type ScGroupProductionWipSummary struct {
	GroupID      int64
	ProductionDt int64
	Wip25pctQty  int64
	Wip50pctQty  int64
	Wip75pctQty  int64
}

type ScGroupTooling struct {
	GroupID       int64
	Effdt         int64
	Enddt         int64
	ItemCd        string
	ItemTechLevel int64
	Retooled      int64
}

type ScGroupUnit struct {
	GroupID    int64
	TechLevel  int64
	Effdt      int64
	Enddt      int64
	NbrOfUnits int64
}

type ScGroupUnitProduction struct {
	GroupID      int64
	TechLevel    int64
	ProductionDt int64
	FuelConsumed int64
	GoldConsumed int64
	MetsConsumed int64
	NmtsConsumed int64
	ProConsumed  int64
	UskConsumed  int64
	AutConsumed  int64
	QtyProduced  int64
}

type ScGroupUnitProductionWip struct {
	GroupID      int64
	TechLevel    int64
	ProductionDt int64
	Wip25pctQty  int64
	Wip50pctQty  int64
	Wip75pctQty  int64
}

type ScInventory struct {
	ScID          int64
	UnitCd        string
	UnitTechLevel int64
	Effdt         int64
	Enddt         int64
	Qty           int64
	Mass          float64
	Volume        float64
	IsAssembled   int64
	IsStored      int64
}

type ScLocation struct {
	ScID        int64
	Effdt       int64
	Enddt       int64
	OrbitID     int64
	IsOnSurface int64
}

type ScMiningSummary struct {
	ScID         int64
	ProductionDt int64
	FuelProduced int64
	GoldProduced int64
	MetsProduced int64
	NmtsProduced int64
}

type ScName struct {
	ScID  int64
	Effdt int64
	Enddt int64
	Name  string
}

type ScPopulation struct {
	ScID         int64
	PopulationCd string
	Effdt        int64
	Enddt        int64
	Qty          int64
	PayRate      float64
	RebelQty     int64
}

type ScProbeOrder struct {
	ID       int64
	ScID     int64
	Effdt    int64
	TargetID int64
	Kind     string
}

type ScProbeStarOrbitResult struct {
	ProbeID   int64
	Effdt     int64
	StarID    int64
	OrbitNo   int64
	OrbitKind string
	FuelEst   int64
	GoldEst   int64
	MetsEst   int64
	NmtsEst   int64
}

type ScProbeStarResult struct {
	ProbeID     int64
	Effdt       int64
	StarID      int64
	Location    string
	NbrOfOrbits int64
}

type ScRates struct {
	ScID      int64
	Effdt     int64
	Enddt     int64
	Rations   float64
	Sol       float64
	BirthRate float64
	DeathRate float64
}

type ScSurveyOrbitResult struct {
	SurveyID       int64
	Effdt          int64
	OrbitID        int64
	Location       string
	OrbitNo        int64
	HabitabilityNo int64
	FarmlandInUse  int64
	Population     int64
}

type ScSurveyOrder struct {
	ID       int64
	ScID     int64
	Effdt    int64
	TargetID int64
	Kind     string
}

type Scs struct {
	ID          int64
	EmpireID    int64
	ScCd        string
	ScTechLevel int64
}

type Stars struct {
	ID          int64
	SystemID    int64
	Sequence    string
	StarName    string
	NbrOfOrbits int64
}

type Systems struct {
	ID         int64
	X          int64
	Y          int64
	Z          int64
	SystemName string
	NbrOfStars int64
}

type UnitCodes struct {
	Code          string
	Name          string
	Category      string
	IsOperational int64
	IsConsumable  int64
	IsResource    int64
	Aliases       sql.NullString
}
