// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"time"
)

type MetaMigration struct {
	Version   int64
	Comment   string
	Script    string
	CreatedAt time.Time
}
