// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: server.sql

package sqlc

import (
	"context"
)

const getSchemaVersion = `-- name: GetSchemaVersion :exec

SELECT max(version)
FROM meta_migrations
`

//	Copyright (c) 2025 Michael D Henderson. All rights reserved.
//
// GetSchemaVersion gets the current schema version.
func (q *Queries) GetSchemaVersion(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, getSchemaVersion)
	return err
}
